Rfairooz/learn
acm-ucr/acm-atlas pull request #100
Opened 2022-08-20 07:18 UTC by rfairooz

The files I changed on my other branch show up here as commits.

2022-08-20 07:21 UTC, shahdivyank requested changes

2022-08-20 07:21 UTC, shahdivyank commented on pages/events.js
> +import Topic from "../components/Topic";
Remove `Topic` from here

2022-08-20 07:21 UTC, shahdivyank commented on pages/events.js
> +			<Topic />
Here too

2022-08-20 07:21 UTC, shahdivyank commented on components/Learn.js
> +		<div className='font-Arial text-lg'>
`font-lexend`

2022-08-20 07:21 UTC, shahdivyank commented on components/Learn.js
> +			<div className='flex justify-center items-center font-Arial font-bold text-4xl mb-4'>
`font-lexend

2022-08-20 07:21 UTC, shahdivyank commented on components/Learn.js
> +				<Col className='flex justify-around'>professional</Col>
Add Topic components in here:


```Javascript

<Col ...>
    <Topic topic = "Resume" color = "cool_color" />
    <Topic topic = "Academics" color = "cool_color" />
</Col>
```

2022-08-20 07:34 UTC, shahdivyank requested changes

2022-08-20 07:34 UTC, shahdivyank commented on components/Learn.js
> +				<Col className='flex justify-around'>
Apply the same styles for each column, for right now, I would just stick with `flex justify-center items-center`

2022-08-20 20:43 UTC, shahdivyank approved these changes

2022-08-21 02:26 UTC, vwong031 approved these changes

2022-08-21 02:55 UTC, merged