introduction
acm-ucr/acm-atlas pull request #108
Opened 2022-08-22 03:03 UTC by vwong031

2022-08-22 08:35 UTC, shahdivyank requested changes
Epic stuff! Regarding the structure of your code. You can simplify it, to having a Row with 2 columns, where the first column has the heading and description and then the second column has the image. Ideally we want the image and text to be in a 50/50 split in terms of space

2022-08-22 08:35 UTC, shahdivyank commented on components/Introduction.js
> +		<Container>
you can remove the `Container` since there is no styling applied and it is not being used

2022-08-22 08:35 UTC, shahdivyank commented on components/Introduction.js
> +					className='text-7xl font-semibold flex justify-center w-75'
dont do `w-75` instead do a percentage like `w-5/6` you can check out the available fractions on the tailwind docs

2022-08-22 08:35 UTC, shahdivyank commented on components/Introduction.js
> +				<Col sm={3} md={3} lg={3} className=''>
remove empty classname

2022-08-22 08:35 UTC, shahdivyank commented on components/Introduction.js
> +						className=''
remove empty classname

2022-08-22 08:35 UTC, shahdivyank commented on components/Introduction.js
> +						src='./acm-ucr-logo.png'
you should just be able to say `src='acm-ucr-logo.png`

2022-08-23 07:55 UTC, shahdivyank submitted a review, later dismissed

2022-08-23 07:55 UTC, shahdivyank commented on components/Introduction.js
> +				<Row className='text-7xl font-semibold flex justify-center mx-auto whitespace-nowrap'>
Use just regular `<p>` tags instead of `<Row>`

2022-08-23 23:17 UTC, shahdivyank approved these changes

2022-08-23 23:18 UTC, Sarah-Rami27 approved these changes

2022-08-23 23:22 UTC, merged