Responsive navbar
acm-ucr/acm-atlas pull request #115
Opened 2022-08-22 14:08 UTC by skyguy-netizen

2022-08-22 14:34 UTC, skyguy-netizen commented
file:///home/aarav/Pictures/Screenshots/Screenshot%20from%202022-08-22%2020-02-39.png
file:///home/aarav/Pictures/Screenshots/Screenshot%20from%202022-08-22%2020-03-03.png
file:///home/aarav/Pictures/Screenshots/Screenshot%20from%202022-08-22%2020-03-11.png

2022-08-22 16:34 UTC, shahdivyank requested changes

2022-08-22 16:34 UTC, shahdivyank commented on components/Navigation.js
> +							src='acmlogo.png'
can you change the image name to `acm-ucr-logo.png` Valerie beat you to the logo naming rights https://github.com/acm-ucr/acm-dev/pull/108

2022-08-22 16:34 UTC, shahdivyank commented on components/Navigation.js
> +					<ul className='navbar-nav ml-auto float-rightmb-2 mb-lg-0'>
add a space

2022-08-22 16:34 UTC, shahdivyank commented on components/Navigation.js
> +							height='40%'
Use Tailwind

2022-08-22 16:34 UTC, shahdivyank commented on components/Navigation.js
> +							alt=''
Add alt text

2022-08-22 16:34 UTC, shahdivyank commented on components/Navigation.js
> +						<li className='nav-item active nav-link font-lexend font-color-black'>
Apply `font-lexend` at the top level `<Navbar/>` and remove from children

2022-08-22 16:34 UTC, shahdivyank commented on components/Navigation.js
> +					<ul className='navbar-nav ml-auto float-rightmb-2 mb-lg-0'>
remove `ui` and `li`, just use the `Link` components

2022-08-22 16:34 UTC, shahdivyank commented on components/Navigation.js
> +		<Navbar collapseOnSelect bg='light' expand='lg'>
make the font-size larger at the top level

2022-08-22 16:34 UTC, shahdivyank commented on components/Navigation.js
> +		<Navbar collapseOnSelect bg='light' expand='lg'>
remove `bg-light` that makes it gray

2022-08-22 18:36 UTC, shahdivyank requested changes

2022-08-22 18:36 UTC, shahdivyank commented on components/Navigation.js
> +				<Nav className='ml-auto nav-item active nav-link float-right mb-2 mb-lg-0 no-underline'>
dont use float, use flex and justify-between

2022-08-22 18:36 UTC, shahdivyank commented on components/Navigation.js
> +						<Nav.Link className='text-black' eventKey='5'>
use `text-acm-black`

2022-08-23 14:48 UTC, skyguy-netizen commented
![Screenshot from 2022-08-23 20-12-14](https://user-images.githubusercontent.com/75974372/186189326-e71a6773-78a5-4254-9d8c-2bb113a785f7.png)
![Screenshot from 2022-08-23 20-12-07](https://user-images.githubusercontent.com/75974372/186189340-7630d636-d0ca-44f2-96f5-07b996e431d0.png)
![Screenshot from 2022-08-23 20-11-42](https://user-images.githubusercontent.com/75974372/186189341-88d44a5b-be35-4c78-a510-27025799a490.png)

2022-08-23 23:38 UTC, shahdivyank commented
Have it collapse on small screens, instead of large

2022-08-24 13:46 UTC, skyguy-netizen commented
![Screenshot from 2022-08-24 19-13-18](https://user-images.githubusercontent.com/75974372/186434582-4dee6ea2-4626-4d1d-b7d0-befd94725aca.png)
![Screenshot from 2022-08-24 19-13-13](https://user-images.githubusercontent.com/75974372/186434595-6fba2ac9-b321-4590-bc10-322745a1c614.png)

2022-08-24 14:43 UTC, shahdivyank approved these changes

2022-08-24 17:02 UTC, Sarah-Rami27 approved these changes

2022-08-24 17:05 UTC, merged