move static data to separate files
acm-ucr/acm-atlas pull request #189
Opened 2022-09-07 20:12 UTC by pondohoo

named the files to where they'll appear next to the component they export to; lmk if there is a better convention

2022-09-08 03:46 UTC, shahdivyank requested changes
can we move all the data files into a folder called `data` just to prevent confusion with components

2022-09-08 16:59 UTC, shahdivyank commented on components/data/CustomToolbarFilters.js
> +export const CustomToolbarFilters = [
rename to Filters

2022-09-08 16:59 UTC, shahdivyank commented on components/data/FooterSocialLinks.js
> +export const FooterSocialLinks = [
Rename to Socials

2022-09-08 16:59 UTC, shahdivyank commented on components/data/OfficersArray.js
> +export const OfficersArray = [
Rename to Officers

2022-09-08 16:59 UTC, shahdivyank commented on components/data/OfficersColors.js
> +export const OfficersColors = [
Rename to Colors

2022-09-09 01:24 UTC, shahdivyank approved these changes

2022-09-09 03:28 UTC, skyguy-netizen approved these changes

2022-09-09 05:17 UTC, merged