Create Mock_Interview.js
acm-ucr/acm-atlas pull request #63
Opened 2022-07-11 01:41 UTC by CJT578078

Signed-off-by: CJT578078 <57580852+CJT578078@users.noreply.github.com>
adding forms to pages

2022-07-11 01:42 UTC, rfairooz approved these changes

2022-07-11 01:43 UTC, pondohoo approved these changes

2022-07-11 01:52 UTC, shahdivyank requested changes
You will have to create an empty React component in order for it to register!
`rafce` or any other arrow functional component will do the trick!

2022-07-13 00:36 UTC, shahdivyank commented
> `Build optimization failed: found page without a React Component as default export in [32](https://github.com/acm-ucr/acm-dev/runs/7274791874?check_suite_focus=true#step:7:33) pages/forms/Mock_Interview`
> 
> You will have to create an empty React component in order for it to register! `rafce` or any other arrow functional component will do the trick!

Fixed!

2022-07-13 00:38 UTC, shahdivyank approved these changes

2022-07-17 20:12 UTC, merged