Sarah rami27/footer/routing
acm-ucr/acm-atlas pull request #72
Opened 2022-07-17 04:50 UTC by Sarah-Rami27

All links under **ACM** go to their respective page except for _Board_. 
Links under **Resources** don't go anywhere for now.

2022-07-17 05:11 UTC, shahdivyank approved these changes

2022-07-19 03:43 UTC, shahdivyank requested changes

2022-07-19 03:43 UTC, shahdivyank commented on components/Footer/Footer.js
>  						<a
Use the `<Link>` tag instead since it is navigation between pages. Using an `<a>` is only used for external links

2022-07-20 02:04 UTC, shahdivyank approved these changes

2022-07-20 02:10 UTC, nicholastengbumroong approved these changes
Looks good 👍

2022-07-20 02:13 UTC, merged