Vwong031/about/gallery
acm-ucr/acm-atlas pull request #73
Opened 2022-07-19 02:39 UTC by vwong031

2022-07-19 03:45 UTC, shahdivyank requested changes

2022-07-19 03:45 UTC, shahdivyank commented on components/About/Gallery.js
> +					src='https://lh3.googleusercontent.com/pw/AM-JKLVv7AS5gdRC3kZ2lN-_QtsiZVKcnfteGQkqnZqANnOmhAxdUEjImIgs_lFf7-L3PnlHPLnUxdkMk80y2kEFCxifGZ4eGddL9gpupz5PFMeTqHuwQ-AYH-tz0TpoP9WErROIPx2Jjo1Sbjx1yfeo
Store the images locally (`public` folder) and reference those images instead

2022-07-20 05:33 UTC, shahdivyank approved these changes

2022-07-20 07:06 UTC, vraimondi04 approved these changes

2022-07-20 19:28 UTC, merged