Sarah rami27/footer
acm-ucr/acm-atlas pull request #88
Opened 2022-08-16 02:10 UTC by Sarah-Rami27

Here's what the footer looks like:
<img width="1302" alt="Screen Shot 2022-08-15 at 7 06 20 PM" src="https://user-images.githubusercontent.com/74696113/184783431-ad95469b-9485-4067-be0a-0578d276c582.png">

Here's what it looks like when you hover over the icons:
<img width="1303" alt="Screen Shot 2022-08-15 at 7 07 26 PM" src="https://user-images.githubusercontent.com/74696113/184783473-956a9c7c-a942-4136-9f0b-7fb591265789.png">
<img width="1303" alt="Screen Shot 2022-08-15 at 7 07 13 PM" src="https://user-images.githubusercontent.com/74696113/184783475-67d20fc8-0476-4034-9f3a-449a72b0a12d.png">
<img width="1303" alt="Screen Shot 2022-08-15 at 7 07 06 PM" src="https://user-images.githubusercontent.com/74696113/184783477-24faf3f3-4f06-4c37-a552-5fd1b42bc034.png">
<img width="1303" alt="Screen Shot 2022-08-15 at 7 07 01 PM" src="https://user-images.githubusercontent.com/74696113/184783478-85d7879b-ed6b-4f11-bb82-18d277e09d71.png">

If the hover colors need to be changed I can fix them.

2022-08-16 05:25 UTC, shahdivyank requested changes
I know the design doesn't include it initially, but can you also add a SLACK, MEDIUM social media icons as well! To tackle the responsiveness problem, I would recommend implementing a Bootstrap Grid system, where each Col is a social media icon. As per width, you can leave it to be a percentage of the entire screen and left Grid handle the margins

2022-08-16 05:25 UTC, shahdivyank commented on components/Footer.js
> +						<svg
What is the SVG for? Can we switch over to using React Icons? Same goes for the path component

2022-08-16 05:25 UTC, shahdivyank commented on components/Footer.js
> +				<h2 className='text-4xl font-lexend font-bold text-center'>
Switch out the `<h2>` for a `<p>` tag

2022-08-16 05:25 UTC, shahdivyank commented on components/Footer.js
> +				<div className='flex flex-wrap justify-center justify-around px-80'>
What is the `justify-around` and `px-80` for? `px-80` is a dangerously large margin value and breaks on mobile, where the icons aren't centered: 
<img width="571" alt="image" src="https://user-images.githubusercontent.com/36285610/184803367-2091495b-d932-44a2-876f-2ccc30cab65a.png">

2022-08-16 05:25 UTC, shahdivyank commented on components/Footer.js
> +						className='w-12 h-12 mx-10 my-6 fill-current md:mx-12 lg:m-0 dark:text-gray-50 hover:text-purple-500'
`w-12` and `h-12` are also dangerous values to be working with and the margin levels as well. Use percentages when possible so its scales nicely, same applies for margins. 

Margins are not enough (to replicate, just try resizing your window): 
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/36285610/184803706-59bf5ff3-ee08-46f9-a09a-8657bc85586a.png">

Breaks into Column Very Quickly:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/36285610/184803798-eb3a4cf2-2f50-4111-9e16-3672636d80a4.png">

2022-08-16 05:26 UTC, shahdivyank requested changes

2022-08-16 05:26 UTC, shahdivyank commented on components/Footer.js
> +		<footer className='dark:bg-neutral-900 dark:text-gray-50 py-6'>
No need to put the `dark:` that is for dark/light themes which is not something we will be doing currently, just `bg-neutral-900` is good!

2022-08-17 00:21 UTC, Sarah-Rami27 commented
What it looks like with the added icons:
<img width="1118" alt="Screen Shot 2022-08-16 at 5 19 38 PM" src="https://user-images.githubusercontent.com/74696113/185007059-61408a9e-a6ba-4f2d-8583-2477e0db7dcf.png">

What it looks like with the screen smaller:
<img width="570" alt="Screen Shot 2022-08-16 at 5 19 55 PM" src="https://user-images.githubusercontent.com/74696113/185007121-76980726-11bf-49d7-bbda-e0099b4487d9.png">

2022-08-17 00:28 UTC, shahdivyank requested changes

2022-08-17 00:28 UTC, shahdivyank commented on components/Footer.js
> +						<div>
What are these div's for? The ones without a class name, you can remove them and just have the a tag. Less code -> lighter website

2022-08-17 00:28 UTC, shahdivyank commented on components/Footer.js
> +			<div className='grid sm:grid-rows-2 justify-center mx-auto'>
Use React Bootstrap Grid with Row and Col components

2022-08-17 00:29 UTC, shahdivyank commented on components/Footer.js
> +			<div className='grid sm:grid-rows-2 justify-center mx-auto'>
https://github.com/acm-ucr/acm-dev/blob/pondohoo/filter/components/Calendar.js 

 Check this example out!

2022-08-17 23:32 UTC, shahdivyank approved these changes

2022-08-17 23:34 UTC, SamuelLin213 approved these changes

2022-08-17 23:36 UTC, merged