create filter component
acm-ucr/acm-atlas pull request #90
Opened 2022-08-16 17:42 UTC by pondohoo

I'm still fairly new to web dev, so let me know of any mistakes I made. Also I wasn't sure if it needed to be a button or not, so I didn't make it one

2022-08-16 17:42 UTC, pondohoo commented
This is what it looks like when I run it
<img width="1025" alt="Screen Shot 2022-08-16 at 10 37 02" src="https://user-images.githubusercontent.com/90938120/184944310-cf653d4b-ab88-4390-8950-4582372cbd81.png">

2022-08-16 18:23 UTC, shahdivyank requested changes

2022-08-16 18:23 UTC, shahdivyank commented on components/Forms/Resume.js
> +import React from "react";
Can you remove this file? I think this is from last time. You can remove any files/folders regarding forms

2022-08-16 18:23 UTC, shahdivyank commented on pages/forms/resume.js
> +import React from "react";
This file can also be removed

2022-08-16 18:23 UTC, shahdivyank commented on components/Filter.js
> +		<div className='w-[270px] h-[55px] flex justify-between bg-black rounded-full'>
Avoid hard coded pixel values, it causes undefined and unpredictable behavior with different screen sizes. instead use percentages

2022-08-16 18:23 UTC, shahdivyank commented on components/Filter.js
> +			<div className='text-white w-9 h-9 self-center ml-5 bg-[#ff5370] rounded-full'></div>
Avoid `w-9`, `ml-5` and `h-9` as they also cause unpredictable behavior with various screen sizes, use percentages instead

2022-08-16 18:23 UTC, shahdivyank commented on components/Filter.js
> +			<div className='font-lexend text-white self-center mr-5'>
Dont use `mr-5`

2022-08-16 18:23 UTC, shahdivyank commented on components/Filter.js
> +const Filter = ({ topic }) => {
Add a color option, since we want them to have different colors and make sure to apply that color as well

2022-08-16 18:24 UTC, shahdivyank commented
Great start! Few changes mostly regarding responsiveness! I added some implementation in the Calendar.js file (you shouldn't need to edit it) that will give you an idea of how much space you will be given, this space is dynamic and will change depending on screen size. So you can use that as a way to test the size of each one. If you think you need more space than 50%, lemme know and we can look into it!

2022-08-17 01:48 UTC, shahdivyank approved these changes
YESSIR!!!! 🎉🎉

2022-08-17 02:00 UTC, skyguy-netizen approved these changes

2022-08-17 02:44 UTC, merged